@echo off
chcp 65001 > nul
setlocal enabledelayedexpansion

:: ========================================
:: YuKyu Dashboard - Installation Script
:: ========================================

title YuKyu Dashboard Installer

cls
echo.
echo  ╔═══════════════════════════════════════════════════════════╗
echo  ║                                                           ║
echo  ║         YuKyu Dashboard - Instalador                      ║
echo  ║         有給休暇管理システム                              ║
echo  ║                                                           ║
echo  ╚═══════════════════════════════════════════════════════════╝
echo.

cd /d "%~dp0"

:: ========================================
:: Check Python
:: ========================================
echo [1/5] Verificando Python...

python --version >nul 2>&1
if errorlevel 1 (
    echo.
    echo    [ERROR] Python no esta instalado!
    echo.
    echo    Pasos para instalar Python:
    echo    1. Ve a https://www.python.org/downloads/
    echo    2. Descarga Python 3.10 o superior
    echo    3. Durante la instalacion, marca "Add Python to PATH"
    echo    4. Reinicia esta terminal y ejecuta install.bat de nuevo
    echo.
    pause
    exit /b 1
)

for /f "tokens=2" %%v in ('python --version 2^>^&1') do set PYTHON_VERSION=%%v
echo    [OK] Python %PYTHON_VERSION%
echo.

:: ========================================
:: Clean Previous Installation
:: ========================================
echo [2/5] Limpiando instalacion anterior...

:: Remove old venv if corrupted
if exist "venv" (
    echo    Eliminando entorno virtual anterior...
    rd /s /q "venv" 2>nul
    timeout /t 2 /nobreak >nul
)

:: Clean cache
for /d /r %%d in (__pycache__) do @if exist "%%d" rd /s /q "%%d" 2>nul
if exist ".pytest_cache" rd /s /q ".pytest_cache" 2>nul
if exist "*.pyc" del /f /q "*.pyc" 2>nul

echo    [OK] Limpieza completada
echo.

:: ========================================
:: Create Virtual Environment
:: ========================================
echo [3/5] Creando entorno virtual...

python -m venv venv
if errorlevel 1 (
    echo    [ERROR] No se pudo crear el entorno virtual
    echo    Intenta ejecutar: python -m pip install --upgrade pip virtualenv
    pause
    exit /b 1
)

call venv\Scripts\activate.bat
echo    [OK] Entorno virtual creado y activado
echo.

:: ========================================
:: Upgrade pip and install dependencies
:: ========================================
echo [4/5] Instalando dependencias...
echo    Esto puede tardar varios minutos...
echo.

:: Upgrade pip
python -m pip install --upgrade pip wheel setuptools

:: Install core dependencies first
echo    Instalando dependencias core...
pip install fastapi uvicorn python-dotenv --quiet

:: Install all dependencies
echo    Instalando todas las dependencias...
pip install -r requirements.txt

if errorlevel 1 (
    echo.
    echo    [WARN] Algunas dependencias fallaron
    echo    Intentando instalacion alternativa...
    pip install -r requirements.txt --no-cache-dir --ignore-installed
)

echo.
echo    [OK] Dependencias instaladas
echo.

:: ========================================
:: Create Configuration Files
:: ========================================
echo [5/5] Configurando proyecto...

:: Create .env
if not exist ".env" (
    (
        echo # YuKyu Dashboard Configuration
        echo # Generated by install.bat
        echo.
        echo # Server
        echo HOST=0.0.0.0
        echo PORT=8000
        echo DEBUG=true
        echo.
        echo # Database
        echo DATABASE_TYPE=sqlite
        echo DATABASE_URL=sqlite:///./yukyu.db
        echo.
        echo # Security
        echo JWT_SECRET_KEY=dev-secret-change-in-production
        echo JWT_ALGORITHM=HS256
        echo JWT_EXPIRATION_HOURS=24
        echo.
        echo # Rate Limiting
        echo RATE_LIMIT_ENABLED=true
        echo RATE_LIMIT_REQUESTS=100
        echo RATE_LIMIT_WINDOW=60
    ) > .env
    echo    [OK] .env creado
)

:: Create exports directory
if not exist "exports" mkdir exports
if not exist "backups" mkdir backups
if not exist "logs" mkdir logs

:: Initialize database
echo    Inicializando base de datos...
python -c "import database; database.init_db()" 2>nul

echo    [OK] Configuracion completada
echo.

:: ========================================
:: Installation Complete
:: ========================================
echo.
echo  ╔═══════════════════════════════════════════════════════════╗
echo  ║                                                           ║
echo  ║         INSTALACION COMPLETADA!                           ║
echo  ║                                                           ║
echo  ╚═══════════════════════════════════════════════════════════╝
echo.
echo   Para iniciar la aplicacion:
echo   1. Ejecuta start.bat
echo   2. O manualmente: python -m uvicorn main:app --reload
echo.
echo   URL: http://localhost:8000
echo   Usuario: admin
echo   Password: admin123456
echo.
echo ════════════════════════════════════════════════════════════
echo.

pause
